---
  - name: installing and launching metricbeat
    hosts: webservers
    become: yes
    tasks:

# Download the .deb file from artifacts.elastic.co.
    - name: download metricbeat deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

# Install the .deb file using the dpkg c
    - name: install metricbeat deb
      command: dpkg -i metricbeat-7.6.1-amd64.deb

# Copy the metricbeat configuration file from your Ansible container to your WebVM's where you just installed metricbeat. Make sure it is copied to: /etc/metricbeat/metricbeat.yml
    - name: drop in metricbeat.yml
      copy:
        src: /etc/ansible/roles/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

 # metricbeat modules enable system

    - name: enable and configure system module
      command: metricbeat modules enable system


# Copy the metricbeat configuration file from your Ansible container to your WebVM's where you just installed metricbeat. Make sure it is copied to: /etc/metricbeat/metricbeat.yml
    - name: drop in metricbeat.yml
      copy:
        src: /etc/ansible/roles/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

# metricbeat setup
    - name: setup metricbeat
      command: metricbeat setup
    - name: start metricbeat service
      command: service metricbeat start

#  Starts metricbeat and enables the on boot
    - name: start metricbeat service
      systemd:
  
    - name: enable metricbeat on boot
      command: systemctl enable metricbeat -e

# metricbeat setup
#    - name: setup metricbeat
#      command: service metricbeat -e start  

# metricbeat start
#    - name: start metricbeat service
#      command: ./metricbeat -e
#    - name: start metricbeat service
#      command: sudo ./metricbeat -e
